### ISSUE TITLE
undefined method `delete!' for nil:NilClass

### ISSUE THREAD

**Issue by pkra** [jekyll/jekyll-seo-tag#202]
Moving this over from https://github.com/github/pages-gem/issues/441.

After updating gh-pages from 134 to 136, I get build errors

      Liquid Exception: undefined method `delete!' for nil:NilClass in /_layouts/default.html

Disabling the SEO plugin resolved this (and was the only relevant update in 136 I could see).

* Link to the source repo: https://github.com/mathjax/mathjax-website
* Link to travis build with same failure (which is used for testing, we let github build the page): https://travis-ci.org/mathjax/MathJax-website/builds/227852201

Any pointers would be welcome.

**Comment by mmistakes** [comment]
I was bit by the same thing. If you add `--verbose` and `--trace` to `jekyll build` it'll help identify what post/page jekyll-seo-tag is breaking on.

In my case I had posts that had unused stuff like `author: false` in their YAML Front Matter. Removing those lines fixed my builds.

@pkra The culprits in your repo seem to be the `author` object. Like in [this post](https://github.com/mathjax/MathJax-website/blob/gh-pages/_posts/2011/2011-09-16-support-from-ieee-boosts-mathjax.md)

```yaml
author:
  login: robertm
  email: stevenp@dessci.com
  display_name: Robert Miner
  first_name: Robert
  last_name: Miner
```

I'm guessing this is all related to the [converting the author stuff](https://github.com/jekyll/jekyll-seo-tag/pull/184) since into a drop: `C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-seo-tag-2.2.2/lib/jekyll-seo-tag/drop.rb:91:in `author': undefined method `delete!' for nil:NilClass (NoMethodErro
r)`

**Comment by pkra** [comment]
Thanks for debugging this for me @mmistakes! And sorry for not looking into how to get better error information from jekyll :bowing_man:.

I should've guessed it's related to [the last bug we ran into](https://github.com/jekyll/jekyll-seo-tag/issues/186#issuecomment-293523148) -- I missed a few posts, apparently.

Leaving it to the maintainers to decide if this is a bug or expected behavior.

**Comment by benbalter** [comment]
Fixed via https://github.com/jekyll/jekyll-seo-tag/pull/203. The problem arises when the post has an `author` hash that contains neither a `name` nor `twitter` key. The plugin is attempting to normalize the non-existent Twitter handle by stripping the `@`.

**Comment by pkra** [comment]
Thanks for the quick response & fix, @benbalter.

**Comment by mbrav** [comment]
Hi, I'm having a similar problem. (appologies for the long ```--trace```) Any suggestions?

```
Liquid Exception: undefined method `+' for nil:NilClass in /_layouts/default.html
bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
NoMethodError: undefined method `+' for nil:NilClass
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-seo-tag-2.2.2/lib/jekyll-seo-tag/drop.rb:43:in `title'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-seo-tag-2.2.2/lib/jekyll-seo-tag/drop.rb:25:in `title?'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/drops/drop.rb:52:in `public_send'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/drops/drop.rb:52:in `[]'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/context.rb:201:in `lookup_and_evaluate'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/variable_lookup.rb:48:in `block in evaluate'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/variable_lookup.rb:38:in `each_index'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/variable_lookup.rb:38:in `evaluate'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/context.rb:168:in `evaluate'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/context.rb:160:in `[]'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/condition.rb:99:in `interpret_condition'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/condition.rb:39:in `evaluate'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/tags/if.rb:38:in `block (2 levels) in render'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/tags/if.rb:37:in `each'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/tags/if.rb:37:in `block in render'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/context.rb:132:in `stack'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/tags/if.rb:36:in `render'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/block.rb:108:in `render'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/template.rb:210:in `block in render'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/template.rb:262:in `with_profiling'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/template.rb:209:in `render'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/template.rb:222:in `render!'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-seo-tag-2.2.2/lib/jekyll-seo-tag.rb:30:in `render'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/block.rb:108:in `render'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/template.rb:210:in `block in render'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/template.rb:262:in `with_profiling'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/template.rb:209:in `render'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/template.rb:222:in `render!'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/liquid_renderer/file.rb:28:in `block (2 levels) in render!'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/liquid_renderer/file.rb:40:in `measure_bytes'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/liquid_renderer/file.rb:27:in `block in render!'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/liquid_renderer/file.rb:47:in `measure_time'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/liquid_renderer/file.rb:26:in `render!'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/tags/include.rb:138:in `block in render'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/context.rb:132:in `stack'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/tags/include.rb:136:in `render'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/block.rb:108:in `render'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/template.rb:210:in `block in render'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/template.rb:262:in `with_profiling'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/template.rb:209:in `render'
  /usr/local/lib/ruby/gems/2.4.0/gems/liquid-3.0.6/lib/liquid/template.rb:222:in `render!'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/liquid_renderer/file.rb:28:in `block (2 levels) in render!'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/liquid_renderer/file.rb:40:in `measure_bytes'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/liquid_renderer/file.rb:27:in `block in render!'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/liquid_renderer/file.rb:47:in `measure_time'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/liquid_renderer/file.rb:26:in `render!'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/renderer.rb:134:in `render_liquid'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/renderer.rb:177:in `place_in_layouts'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/renderer.rb:91:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:452:in `block (2 levels) in render_docs'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:450:in `each'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:450:in `block in render_docs'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:449:in `each'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:449:in `render_docs'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:190:in `render'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:69:in `process'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/command.rb:26:in `process_site'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/commands/build.rb:63:in `build'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/commands/build.rb:34:in `process'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/commands/serve.rb:37:in `block (2 levels) in init_with_program'
  /usr/local/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /usr/local/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /usr/local/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /usr/local/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /usr/local/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/exe/jekyll:13:in `<top (required)>'
  /usr/local/bin/jekyll:22:in `load'
  /usr/local/bin/jekyll:22:in `<top (required)>'

```
